### ISSUE TITLE
WP uses texturize and kses engines?

### ISSUE THREAD

**Issue by saidbakr** [benbalter/Convert-Word-Documents-to-HTML#1]
I think that the docs should show or link to how to make WP uses texturize and kses engines?

**Comment by benbalter** [comment]
@saidbakr this project is no longer maintained. If you still need to convert word to HTML, I'd take a look at https://github.com/benbalter/word-to-markdown, which can be used to go from Markdown to HTML, or also converts the word documents to **much** cleaner HTML as an intermediary step.
